---
title: "*MOSAIC Calculus*"
subtitle: "Instructor Notes"
site: distill::distill_website
---

The Project MOSAIC [calculus textbook](https://projectmosaic.github.io/MOSAIC-Calculus) is divided into six blocks and a collection of "manifestations." Depending on the goals for the course being taught different blocks can be included.

- Preface: What is calculus?

- [Block 1: Introduction to functions and computing](Block-1.html)

- [Block 1b: Foundations for modeling](Block-2.html)
    - Project: [Lessons from Ebola](Projects/Lessons-from-ebola/Lessons-from-ebola.html)

- [Block 2: Differentiation](Block-3.html)
    - Projects:
        - [How fast does a bicycle go?](Projects/Biking/Biking-speed.html)
        - [How to walk uphill](Projects/Walking/Walking-uphill.html)

- [Block 3: Anti-differentiation and accumulation](Block-4.html)
    - Project: [Driving with integrals](Projects/Fuel-consumption/narrative.html)

- [Block 4: Manifestations](manifestations.html)
    i. Operations on functions
    ii. Interpolation and splines
    iii. Optimization and constraint
    iv. Probability and evidence
    v. Present and future value
        - Project: [Retirement and after](Projects/Retirement/retirement.html)
    vi. Mechanics

- [Block 5: Linear combinations](Block-5/Block-5.html)
    - Project: [Least squares and engine scaling](Projects/Engine-scaling/Engine-scaling.html)

- [Block 6: Dynamics](Block-6/Block-6.html)
    - Project: [Using a model to set policy](Projects/SIR-model/using-the-SIR-model.html)


    
-----

[Writing for this blog](writing-instructions.html)

[Keeping track of objectives](ObjectiveTracking/Using-objectives.html)
