---
title: "Overview of Block 5"
description: |
  Motivation and objectives of Block 5
author:
  - name: Daniel Kaplan
date: 2022-01-27
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The instructor can easily see that the Block-5 chapters are about linear algebra. But the word "algebra" is missing in the title of the block. Instead, the title is *Linear Combinations*. In part, this is intended to help unify the text, since linear combinations appear in all of the first 4 Blocks. But also the title was selected because the canonical topics found in just about any linear algebra book are not included---for good reason.

- matrices as rectangular arrays of numbers
- gaussian elimination
- determinants
- inverses

Keep in mind that in a traditional curriculum, linear algebra is a fourth or fifth course in a calculus sequence. This means that very few students ever take it and, consequently, that few downstream courses outside of advanced mathematics make use of it. (Differential equations is an exception, but you'll see the use of more linear algebra concepts such as eigenvalues and eigenvectors in Block 6.)

There are two introductory subjects that make (or could make) use of linear algebra concepts:

- Introductory physics, where the decomposition of vectors into orthogonal components is used in many basic mechanics examples.
- Introductory statistics. In modern introductory statistics courses, *modeling* is an important component of the course, not just simple regression but multiple regression. In explaining topics such as the F-statistic, classical inference is based on dividing up a high-dimensional vector space into model and residual components.


## The software

`rbind()`, `cbind()`, `%dot%` and so on.



